In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns 
import matplotlib.pyplot as plt
%matplotlib inline
data = pd.read_csv(("C:/Users/kgopalu/Desktop/Kaggle_Titanic/train.csv"))
testing_predictions = pd.read_csv(("C:/Users/kgopalu/Desktop/Kaggle_Titanic/test.csv"))
for i in data:
    data['Initial']=data.Name.str.extract('([A-Za-z]+)\.')

data.head()
data['Age'] = data.groupby('Initial')['Age'].apply(lambda x: x.fillna(x.mean()))
data['NewSibSp'] = 5 # let something more than 5 be 5 (others)

data.loc[(data.SibSp.values == 0),'NewSibSp']= 0
data.loc[(data.SibSp.values == 1),'NewSibSp']= 1
data.loc[(data.SibSp.values == 2),'NewSibSp']= 2
data.loc[(data.SibSp.values == 3),'NewSibSp']= 3
data.loc[(data.SibSp.values == 4),'NewSibSp']= 4

data['NewParch'] = 3 # let something more than 3 be 3 (others)

data.loc[(data.Parch.values == 0),'NewParch']= 0
data.loc[(data.Parch.values == 1),'NewParch']= 1
data.loc[(data.Parch.values == 2),'NewParch']= 2

data['Agroup'] = 1

data.loc[(data.Age.values < 24.0),'Agroup']= 0
data.loc[(data.Age.values > 30.0),'Agroup']= 2


data['Fgroup'] = 1

data.loc[(data.Fare.values >10),'Fgroup']= 2
data.loc[(data.Fare.values >25),'Fgroup']= 3
data.loc[(data.Fare.values >50),'Fgroup']= 4
data.loc[(data.Fare.values >75),'Fgroup']= 5

data = data.drop(['PassengerId'], axis = 1)
data = data.drop(['Age'], axis = 1)
data = data.drop(['Parch'], axis = 1)
data = data.drop(['SibSp'], axis = 1)
data = data.drop(['Fare'], axis = 1)
data = data.drop(['Name'], axis = 1)
data = data.drop(['Ticket'], axis = 1)
data = data.drop(['Cabin'], axis = 1)
data=pd.get_dummies(data)
data.head()

X = data.drop(['Survived'], axis = 1)
#X = data[['Pclass','Agroup','NewSibSp','NewParch','Fgroup']]
y = data[['Survived']]
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0)

from numpy import loadtxt
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

model = XGBClassifier()
model.fit(X_train, y_train)
XGboost_pred=model.predict(X_test)
XGboost_cm=confusion_matrix(y_test,XGboost_pred)
XGboost_ac=accuracy_score(XGboost_pred,y_test)
print("XGboost_ac: %.2f%%" % (XGboost_ac * 100.0))
print(XGboost_cm)

C:\Users\kgopalu\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\kgopalu\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


XGboost_ac: 83.80%
[[97 13]
 [16 53]]


In [12]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns 
import matplotlib.pyplot as plt
%matplotlib inline
data = pd.read_csv(("C:/Users/kgopalu/Desktop/Kaggle_Titanic/train.csv"))
testing_predictions = pd.read_csv(("C:/Users/kgopalu/Desktop/Kaggle_Titanic/test.csv"))

data = data.drop(['PassengerId'], axis = 1)
data = data.drop(['Name'], axis = 1)
data = data.drop(['Ticket'], axis = 1)
data = data.drop(['Cabin'], axis = 1)

data=pd.get_dummies(data)


X = data.drop(['Survived'], axis = 1)
#X = data[['Pclass','Agroup','NewSibSp','NewParch','Fgroup']]
y = data[['Survived']]
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0)

from numpy import loadtxt
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

model = XGBClassifier()
model.fit(X_train, y_train)
XGboost_pred=model.predict(X_test)
XGboost_cm=confusion_matrix(y_test,XGboost_pred)
XGboost_ac=accuracy_score(XGboost_pred,y_test)
print("XGboost_ac: %.2f%%" % (XGboost_ac * 100.0))
print(XGboost_cm)

XGboost_ac: 84.36%
[[99 11]
 [17 52]]


In [13]:
data = pd.read_csv(("C:/Users/kgopalu/Desktop/Kaggle_Titanic/test.csv"))
data = data.drop(['PassengerId'], axis = 1)
data = data.drop(['Name'], axis = 1)
data = data.drop(['Ticket'], axis = 1)
data = data.drop(['Cabin'], axis = 1)
data=pd.get_dummies(data)
XGboost_pred_val=model.predict(X_test)

In [14]:
XGboost_pred_val

array([0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1], dtype=int64)